
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMasMenosleftPorEntreAsigna Coma Dif Entre FIN ID INICIO Mas Mayor Mayorigual Menor Menorigual Menos Numero Por Punto Si const derpar entonces hacer izpar mientras print puntocoma varprograma : INICIO cuerpo FIN programa_end\n    programa_end :\n    \n    expresion : Numero Punto Numero\n    cuerpo : lista_declaracioneslista_declaraciones : lista_declaraciones declaracion\n                           | declaraciondeclaracion : tipo lista_variables puntocomatipo : const\n            | varlista_variables : lista_variables Coma ID\n                       | IDasignacion : ID Asigna expresion puntocomaestructura_control : sentencia_if\n                          | sentencia_whilesentencia_if : Si condicion entonces cuerpo FINsentencia_while : mientras condicion hacer cuerpo FINcondicion : expresion comparador expresioncomparador : Menor\n                  | Mayor\n                  | Menorigual\n                  | Mayorigual\n                  | Difexpresion : expresion Mas expresion\n                 | expresion Menos expresion\n                 | expresion Por expresion\n                 | expresion Entre expresion\n                 | ID\n                 | Numero\n                 | izpar expresion derparescritura : print izpar expresion derpar puntocoma'
    
_lr_action_items = {'INICIO':([0,],[2,]),'$end':([1,9,13,],[0,-2,-1,]),'const':([2,4,5,10,14,],[7,7,-6,-5,-7,]),'var':([2,4,5,10,14,],[8,8,-6,-5,-7,]),'FIN':([3,4,5,10,14,],[9,-4,-6,-5,-7,]),'ID':([6,7,8,15,],[12,-8,-9,16,]),'puntocoma':([11,12,16,],[14,-11,-10,]),'Coma':([11,12,16,],[15,-11,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'cuerpo':([2,],[3,]),'lista_declaraciones':([2,],[4,]),'declaracion':([2,4,],[5,10,]),'tipo':([2,4,],[6,6,]),'lista_variables':([6,],[11,]),'programa_end':([9,],[13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> INICIO cuerpo FIN programa_end','programa',4,'p_programa','compyv2.py',56),
  ('programa_end -> <empty>','programa_end',0,'p_programa_end','compyv2.py',61),
  ('expresion -> Numero Punto Numero','expresion',3,'p_expresion_decimal','compyv2.py',68),
  ('cuerpo -> lista_declaraciones','cuerpo',1,'p_cuerpo','compyv2.py',73),
  ('lista_declaraciones -> lista_declaraciones declaracion','lista_declaraciones',2,'p_lista_declaraciones','compyv2.py',77),
  ('lista_declaraciones -> declaracion','lista_declaraciones',1,'p_lista_declaraciones','compyv2.py',78),
  ('declaracion -> tipo lista_variables puntocoma','declaracion',3,'p_declaracion','compyv2.py',82),
  ('tipo -> const','tipo',1,'p_tipo','compyv2.py',86),
  ('tipo -> var','tipo',1,'p_tipo','compyv2.py',87),
  ('lista_variables -> lista_variables Coma ID','lista_variables',3,'p_lista_variables','compyv2.py',91),
  ('lista_variables -> ID','lista_variables',1,'p_lista_variables','compyv2.py',92),
  ('asignacion -> ID Asigna expresion puntocoma','asignacion',4,'p_asignacion','compyv2.py',97),
  ('estructura_control -> sentencia_if','estructura_control',1,'p_estructura_control','compyv2.py',101),
  ('estructura_control -> sentencia_while','estructura_control',1,'p_estructura_control','compyv2.py',102),
  ('sentencia_if -> Si condicion entonces cuerpo FIN','sentencia_if',5,'p_sentencia_if','compyv2.py',106),
  ('sentencia_while -> mientras condicion hacer cuerpo FIN','sentencia_while',5,'p_sentencia_while','compyv2.py',110),
  ('condicion -> expresion comparador expresion','condicion',3,'p_condicion','compyv2.py',114),
  ('comparador -> Menor','comparador',1,'p_comparador','compyv2.py',118),
  ('comparador -> Mayor','comparador',1,'p_comparador','compyv2.py',119),
  ('comparador -> Menorigual','comparador',1,'p_comparador','compyv2.py',120),
  ('comparador -> Mayorigual','comparador',1,'p_comparador','compyv2.py',121),
  ('comparador -> Dif','comparador',1,'p_comparador','compyv2.py',122),
  ('expresion -> expresion Mas expresion','expresion',3,'p_expresion','compyv2.py',126),
  ('expresion -> expresion Menos expresion','expresion',3,'p_expresion','compyv2.py',127),
  ('expresion -> expresion Por expresion','expresion',3,'p_expresion','compyv2.py',128),
  ('expresion -> expresion Entre expresion','expresion',3,'p_expresion','compyv2.py',129),
  ('expresion -> ID','expresion',1,'p_expresion','compyv2.py',130),
  ('expresion -> Numero','expresion',1,'p_expresion','compyv2.py',131),
  ('expresion -> izpar expresion derpar','expresion',3,'p_expresion','compyv2.py',132),
  ('escritura -> print izpar expresion derpar puntocoma','escritura',5,'p_escritura','compyv2.py',136),
]
